[package]
name = "probers-macros"
version = "0.1.0"
authors = ["Adam Nelson <anelson@users.noreply.github.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
proc-macro-hack = "0.5"
probers-macros-hack = { path = "../probers-macros-hack", version = "0.1.0" }

