freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  name: FreeBSD 12.0 amd64
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
  cargo_cache:
    folder: $HOME/.cargo/registry
  build_script:
    - . $HOME/.cargo/env
    - cargo build --manifest-path tracers/Cargo.toml
    - cargo build --manifest-path tracers/Cargo.toml --no-default-features
  test_script:
    - . $HOME/.cargo/env
    - TRACERS_EXPECTED_DYNAMIC_IMPL=DISABLED TRACERS_EXPECTED_PROVIDER=tracers_test_probes::static/static_noop::0.1.0 cargo test --manifest-path tracers/Cargo.toml
    - TRACERS_EXPECTED_DYNAMIC_IMPL=DISABLED TRACERS_EXPECTED_PROVIDER=tracers_test_probes::disabled::0.1.0 cargo test --manifest-path tracers/Cargo.toml --no-default-features
  bench_script:
    - . $HOME/.cargo/env
    - cargo bench --manifest-path tracers/Cargo.toml
    - cargo bench --manifest-path tracers/Cargo.toml --no-default-features
  before_cache_script:
    - rm -rf $HOME/.cargo/registry/index
