[workspace]
members = [
    "libelf-sys",
    "libstapsdt-sys",
    "probers-build",
    "probers-codegen",
    "probers-core",
    "probers-macros",
    "probers-noop",
    "probers-stap",
    "probers"
]
