[workspace]
members = [
    "libelf-sys",
    "libstapsdt-sys",
    "tracers-build",
    "tracers-codegen",
    "tracers-core",
    "tracers-macros",
    "tracers-macros-hack",
    "tracers-dyn-noop",
    "tracers-dyn-stap",
    "tracers",

    "examples/simple"
]
