[package]
name = "probers"
version = "0.1.0"
authors = ["Adam Nelson <anelson@users.noreply.github.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[badges]
maintenance = { status = "experimental" }

[workspace]
exclude = ["probers-stap", "libstapsdt-sys", "libelf-sys"]

[dependencies]
probers-core = { path = "probers-core", version = "0.1.0" }
probers-macros = { path = "probers-macros", version = "0.1.0" }

# This is only a fallback; not always used
probers-noop = { path = "probers-noop", version = "0.1.0" }

proc-macro-hack = "0.5"

[dev-dependencies]
failure = "0.1.5"
once_cell = "0.1.8"

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.dependencies]
probers-stap = { path = "probers-stap", version = "0.1.0" }

