[package]
name = "probe-rs"
version = "0.1.0"
authors = ["Adam Nelson <anelson@users.noreply.github.com>"]
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
probers-core = { path = "probers-core", version = "0.1.0" }
probers-macros = { path = "probers-macros", version = "0.1.0" }

[dev-dependencies]
failure = "0.1.5"
once_cell = "0.1.8"

[target.'cfg(all(target_arch = "x86_64", target_os = "linux"))'.dependencies]
probers-stap = { path = "probers-stap", version = "0.1.0" }

