[workspace]
members = [
    "libelf-sys",
    "libstapsdt-sys",
    "probers-build",
    "probers-codegen",
    "probers-core",
    "probers-macros",
    "probers-macros-hack",
    "probers-dyn-noop",
    "probers-dyn-stap",
    "probers",

    "examples/simple"
]
